repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide
        entry: flake8
        language: python
        args: ["--config=setup.cfg"]
        types: [python]